# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Realease

on:
  push:
    branches: [ "release" ]
  # pull_request:
  #   branches: [ "release" ]
  #   types: [ closed ]
permissions: write-all
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r -j ./chrome-extension.zip dir
    - run: npm run semantic-release
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: Dist
    #     path: dist
    # - run: npm test
